// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwnjzvqbxoatmudnvdcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bmp6dnFieG9hdG11ZG52ZGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDcwMTUsImV4cCI6MjA2OTUyMzAxNX0.PnIiJXVzSLG2Xmf3h3mC0QYy_zBkR7TTS6x2M4_Loec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});